import { GoogleGenAI, Type } from "@google/genai";
import { RecipeResponse } from "../types";

const apiKey = process.env.API_KEY || '';
const ai = new GoogleGenAI({ apiKey });

// Helper to encode file to base64
export const fileToGenerativePart = async (file: File): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      // Remove data url prefix (e.g. "data:image/jpeg;base64,")
      const base64Data = base64String.split(',')[1];
      resolve(base64Data);
    };
    reader.onerror = reject;
    reader.readAsDataURL(file);
  });
};

export const generateRecipe = async (dishName: string): Promise<RecipeResponse> => {
  const model = "gemini-2.5-flash";
  
  const response = await ai.models.generateContent({
    model,
    contents: `I want to cook "${dishName}". You are an assistant for "Hemmati Supermarket". List the ingredients I need to buy and simple instructions. Respond in Persian (Farsi).`,
    config: {
      responseMimeType: "application/json",
      responseSchema: {
        type: Type.OBJECT,
        properties: {
          dishName: { type: Type.STRING },
          cookingTime: { type: Type.STRING, description: "Estimated cooking time" },
          ingredients: {
            type: Type.ARRAY,
            items: {
              type: Type.OBJECT,
              properties: {
                name: { type: Type.STRING },
                amount: { type: Type.STRING },
                category: { type: Type.STRING, description: "e.g., Dairy, Produce, Meat" }
              }
            }
          },
          instructions: {
            type: Type.ARRAY,
            items: { type: Type.STRING }
          }
        }
      }
    }
  });

  if (response.text) {
    return JSON.parse(response.text) as RecipeResponse;
  }
  throw new Error("No recipe generated");
};

export const editImage = async (imageFile: File, prompt: string): Promise<string> => {
  // Using gemini-2.5-flash-image (Nano Banana) for image editing tasks
  const model = "gemini-2.5-flash-image";
  
  const base64Data = await fileToGenerativePart(imageFile);
  
  const response = await ai.models.generateContent({
    model,
    contents: {
      parts: [
        {
          inlineData: {
            mimeType: imageFile.type,
            data: base64Data
          }
        },
        {
          text: prompt
        }
      ]
    }
  });

  // Extract the generated image from the response
  for (const part of response.candidates?.[0]?.content?.parts || []) {
    if (part.inlineData) {
      return `data:image/png;base64,${part.inlineData.data}`;
    }
  }

  throw new Error("No image generated by the model");
};

export const generateDietPlan = async (height: string, weight: string, age: string, gender: string): Promise<string> => {
  const model = "gemini-2.5-flash";
  const prompt = `
    من یک کاربر ایرانی هستم با مشخصات زیر:
    قد: ${height} سانتی‌متر
    وزن: ${weight} کیلوگرم
    سن: ${age} سال
    جنسیت: ${gender === 'male' ? 'مرد' : 'زن'}
    
    به عنوان مشاور تغذیه هوشمند:
    ۱. ابتدا BMI من را حساب کن و بگو در کدام دسته (کمبود وزن، نرمال، اضافه وزن یا چاق) هستم.
    ۲. **منطق رژیم:**
       - اگر "کمبود وزن" دارم: حتما یک رژیم **افزایش وزن (چاقی)** پرکالری و مقوی بده.
       - اگر "اضافه وزن" یا "چاق" هستم: حتما یک رژیم **کاهش وزن (لاغری)** چربی‌سوز بده.
       - اگر "نرمال" هستم: یک رژیم سالم برای حفظ تناسب اندام بده.
    
    ۳. یک برنامه غذایی یک روزه (صبحانه، نهار، شام، میان‌وعده) با غذاهای در دسترس ایرانی پیشنهاد بده.
    
    **نکته مهم:** پاسخ باید **کوتاه، خلاصه و بسیار کاربردی** باشد. از توضیحات طولانی علمی پرهیز کن و سریع برو سر اصل مطلب.
  `;
  
  const response = await ai.models.generateContent({
    model,
    contents: prompt,
  });

  return response.text || "متاسفانه مشکلی در تولید برنامه پیش آمد.";
};
